---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Análise Álysse e Lizandra

## Citação do R

```{r}
citation()
```


## Carregando pacotes

```{r,message=FALSE,error=FALSE,warning=FALSE}
library(readxl)
library(tidyverse)
library(ExpDes.pt)
```


## Entrada de dados

```{r,message=FALSE,error=FALSE,warning=FALSE}
macro<- read_excel("data/Analise morfo macro.xlsx",na = "NA") |> 
  janitor::clean_names()
glimpse(macro)
```

```{r,message=FALSE,error=FALSE,warning=FALSE}
micro<- read_excel("data/Analise morfo micro.xlsx",na = "NA")|> 
  janitor::clean_names()
glimpse(micro)
```


## Análise para MACRO

```{r}
for(i in 4:length(macro)){
  y <- macro[i] |>  pull()
  print("######################################")
  print(paste0("Análise para: ",names(macro[i])))
  print("######################################")
  criptorquida <- macro[2] |>  pull() |> as.factor()
  dic(criptorquida[!is.na(y)], y[!is.na(y)])
  }
```


## Análise para MICRO

```{r}
micro_aux <- micro |> 
  group_by(nome, criptorquida) |> 
  summarise(
    al_ta_test = mean(al_ta_test, na.rm=TRUE),
    diam_ts_test = mean(diam_ts_test, na.rm=TRUE),
    ept_ts_test = mean(ept_ts_test, na.rm=TRUE),
    diam_co_ep = mean(diam_co_ep, na.rm=TRUE),
    ept_co_ep = mean(ept_co_ep, na.rm=TRUE),
    diam_ca_ep = mean(diam_ca_ep, na.rm=TRUE),
    ept_ca_ep = mean(ept_ca_ep, na.rm=TRUE)
  )

for(i in 3:length(micro_aux)){
  y <- micro_aux[i] |>  pull()
  print("######################################")
  print(paste0("Análise para: ",names(micro_aux[i])))
  print("######################################")
  criptorquida <- micro_aux[2] |>  pull() |> as.factor()
  dic(criptorquida[!is.na(y)], y[!is.na(y)],mcomp = "tukey")
  }

```
 






